### ISSUE TITLE
"Uncaught Error: Bad state: Future already completed" when "SELECT"ing a .png

### ISSUE THREAD

**Issue by thaden0** [jamesots/sqljocky#39]
When saving a .PNG file that is 4630 bytes there is no issue. The data is in a LONGBLOB.

mysql --version: 
*mysql  Ver 15.1 Distrib 5.5.37-MariaDB, for Linux (x86_64) using readline 5.1*

the actual query used is:
*SELECT * FROM content WHERE pathRaw=?;*
*["social/logo.png"]*

The Stack Trace:
Uncaught Error: Bad state: Future already completed
Stack Trace: 
#0      _AsyncCompleter.completeError (dart:async/future_impl.dart:35)
#1      _handleData (package:sqljocky/src/connection.dart:211:31)
#2      _rootRunUnary (dart:async/zone.dart:730)
#3      _RootZone.runUnary (dart:async/zone.dart:864)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:488)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:571)
#6      _Future._completeWithValue (dart:async/future_impl.dart:331)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:393)
#8      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:23)
#9      _asyncRunCallback (dart:async/schedule_microtask.dart:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:119)

in ShutdownIsolate: Unhandled exception:
Bad state: Future already completed
#0      _rootHandleUncaughtError.<anonymous closure>.<anonymous closure> (dart:async/zone.dart:713)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:23)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:32)
#3      _asyncRunCallback (dart:async/schedule_microtask.dart:36)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:119)

**Comment by Bees-Knees** [comment]
Why is this still not fixed? It prevents everybody from using blobs. :(

**Comment by jamesots** [comment]
This is hopefully resolved in the latest commit.
