### ISSUE TITLE
Blob (list of int) read write problem

### ISSUE THREAD

**Issue by brunoleguernic** [jamesots/sqljocky#53]
Hi,
When i read ( or write) a binary blob i have the error:
FormatException: Bad UTF-8 encoding 0xe3
Stack Trace:
#0      _Utf8Decoder.convert (dart:convert/utf.dart:455)
#1      Utf8Decoder.convert (dart:convert/utf.dart:322)
#2      Utf8Codec.decode (dart:convert/utf.dart:66)
#3      Blob.toString (package:sqljocky/src/blob.dart:30:23)
#4      _StringBase._interpolate (dart:core-patch/string_patch.dart:589)
#5      _ExecuteQueryHandler._writeBlob (package:sqljocky/src/prepared_statements/execute_query_handler.dart:137:28)
#6      _ExecuteQueryHandler._writeValue (package:sqljocky/src/prepared_statements/execute_query_handler.dart:54:19)
#7      _ExecuteQueryHandler.createRequest (package:sqljocky/src/prepared_statements/execute_query_handler.dart:30:18)
#8      _Connection.processHandler (package:sqljocky/src/connection.dart:290:38)
#9      Query._execute (package:sqljocky/src/query.dart:118:37)
#10     Query.executeMulti.<anonymous closure>.executeQuery (package:sqljocky/src/query.dart:145:19)
#11     Query.executeMulti.<anonymous closure> (package:sqljocky/src/query.dart:161:21)
#12     _RootZone.runUnary (dart:async/zone.dart:1155)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#15     _Future._completeWithValue (dart:async/future_impl.dart:358)
#16     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#17     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#18     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)

I modified your sample like this.
 Future createTables() {
    print("creating tables");
    var querier = new QueryRunner(pool, ['create table people (id integer not null auto_increment, '
                                        'name varchar(255), '
                                        'age integer, '
                                        'primary key (id))',
                                        
                                        'create table pets (id integer not null auto_increment, '
                                        'name varchar(255), '
                                        'species text, '
                                        'infos blob,'
                                        'owner_id integer, '
                                        'primary key (id),'
                                        'foreign key (owner_id) references people (id))'
                                        ]);
    print("executing queries");
    return querier.executeQueries();
  }
Future addData() {
    var completer = new Completer();
    pool.prepare("insert into people (name, age) values (?, ?)").then((query) {
      print("prepared query 1");
      var parameters = [
          ["Dave", 15],
          ["John", 16],
          ["Mavis", 93]
        ];
      return query.executeMulti(parameters);
    }).then((results) {
      print("executed query 1");
      return pool.prepare("insert into pets (name, species, infos , owner_id) values (?, ?, ?, ?)");
    }).then((query) {
      print("prepared query 2");
      File FileDocDog= new File("dog.pdf");
      File FileDocCow= new File("cow.jpg");
      FileDocDog.readAsBytes().then((List<int> innerFileDog){
        FileDocCow.readAsBytes().then((List<int> innerFileCow){
          Blob blobDog = new Blob.fromBytes(innerFileDog);
          Blob blobCow = new Blob.fromBytes(innerFileCow);
          var parameters = [
              ["Rover", "Dog", blobDog ,1],
              ["Daisy", "Cow", blobCow , 2],
              ["Spot", "Dog", blobDog, 2]];
    //          ["Spot", "D\u0000og", 2]];
          return query.executeMulti(parameters);
        });
      });
    }).then((results) {
      print("executed query 2");
      completer.complete(null);
    });
    return completer.future;
  }

I try also to read a blob, i have the same problem. ( I put the blob value with phpmyadmin)
Thank you.
Bruno LE GUERNIC.

**Comment by jamesots** [comment]
This is hopefully resolved in the latest commit.
