### ISSUE TITLE
Handle Connection Timeouts

### ISSUE THREAD

**Issue by sonoranDesert** [jamesots/sqljocky#54]
I see on your front page that this is on your to-do list.

sqljocky is a good package, but it would be even better if I could worry less about the status of database connections, somehow.

I'm not certain how this would work, nor exactly what should still be necessary for the user to do, but I feel like timeouts could probably be handled more effectively on the sqljocky side.

**Comment by LucWollants** [comment]
I deployed an application to Heroku and got timeout issues "SocketException: OS Error: Connection timed out, errno = 110, address = ..."

Also see stackoverflow for more details: http://stackoverflow.com/questions/32045950/does-the-connectionpool-from-sqljocky-require-a-close

The Heroku infrastructure forces an idle connection after 1 minute. I am using a connection pool and the next fired SQL execute after this timeout will get an error.

**Comment by jamesots** [comment]
Timeouts are handled a little better now, in that if the server closes the connection then the socket will be released in sqljocky so that it can be reused without an error.
