### ISSUE TITLE
Query fails if the first field in SELECT is a blank string

### ISSUE THREAD

**Issue by astashov** [jamesots/sqljocky#56]
If we have a table like this:

```sql
CREATE TABLE row (id INTEGER, name TEXT, length INTEGER);
INSERT INTO row (id, name, length) VALUES (1, "", 5000);
```

Then:

```dart
final results = await (await pool.query("SELECT name, length FROM row")).toList();
```

will result with:

```
Uncaught Error: Bad state: Future already completed
```

And according to logs, it happens because the response from MySQL looks like this:

```
00 04 35 30  30 30         ··5000
```

i.e. it starts with `00`, which is considered as `okPacket`, but should be considered as `rowPacket`.

Interesting though, if we add a row like this:

```sql
INSERT INTO row (id, name, length) VALUES (1, "foo", 5000);
```

then the response will be

```
03 66 6f 6f  04 35 30 30   ·foo·500
30                         0 
```

I.e. will start with non `00`, and will be handled correctly.

**Comment by astashov** [comment]
Oh, and my mysql version is:

```bash
$ mysql --version
mysql  Ver 14.14 Distrib 5.6.10, for osx10.8 (x86_64) using  EditLine wrapper
```

**Comment by astashov** [comment]
Could you please publish it on pub as well once you have a chance?

**Comment by jamesots** [comment]
Yes, have done :)

**Comment by astashov** [comment]
Awesome, thanks!
