### ISSUE TITLE
Version of logging on Pub is outdated.

### ISSUE THREAD

**Issue by eugene-bulkin** [jamesots/sqljocky#60]
The pubspec.yaml was updated to reflect the new version in 96408be07534e7bfdccc21081b8d0946c55efd96, but it was updated in 61a1cec888412127cec14cc2ef91a5c2a8aa150b. It appears that pub was never updated with this (i.e. I cannot use logging > 0.10.0 and still use sqljocky). Can sqljocky be re-published on pub?

I would imagine since new things have been added, this would be worth bumping the version to 0.13.1 and then publishing, but either way, it's essentially impossible to use some libraries with sqljocky right now because the new dependencies are not published to pub.

**Comment by jamesots** [comment]
I've just published v0.14 which uses the new logging library
